using Microsoft.Maui.Media;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaCamp.Resources.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaCamp.Resources.Locale.AppLanguage", typeof(AppLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a picture from the gallery.
        /// </summary>
        public static string Escolher_foto_galeria {
            get {
                return ResourceManager.GetString("Escolher_foto_galeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a video from the gallery.
        /// </summary>
        public static string Escolher_video_galeria {
            get {
                return ResourceManager.GetString("Escolher_video_galeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not access the camera at this moment..
        /// </summary>
        public static string Mensagem_CameraNaoDisponivel {
            get {
                return ResourceManager.GetString("Mensagem_CameraNaoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permissions are required to obtain the picture..
        /// </summary>
        public static string Mensagem_PermissaoFotoNegada {
            get {
                return ResourceManager.GetString("Mensagem_PermissaoFotoNegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a picture.
        /// </summary>
        public static string SelecioneUmaFoto {
            get {
                return ResourceManager.GetString("SelecioneUmaFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a picture or a video.
        /// </summary>
        public static string SelecioneUmaFotoOuVideo {
            get {
                return ResourceManager.GetString("SelecioneUmaFotoOuVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Texto_BemVindo {
            get {
                return ResourceManager.GetString("Texto_BemVindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Texto_Compartilhar {
            get {
                return ResourceManager.GetString("Texto_Compartilhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string Texto_Favoritar {
            get {
                return ResourceManager.GetString("Texto_Favoritar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorites.
        /// </summary>
        public static string Texto_Remover_Favorito {
            get {
                return ResourceManager.GetString("Texto_Remover_Favorito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text has translations.
        /// </summary>
        public static string Texto_Texto_multi_idioma {
            get {
                return ResourceManager.GetString("Texto_Texto_multi_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        public static string Texto_Tirar_uma_foto {
            get {
                return ResourceManager.GetString("Texto_Tirar_uma_foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Texto_Voltar {
            get {
                return ResourceManager.GetString("Texto_Voltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not available.
        /// </summary>
        public static string Titulo_CameraNaoDisponivel {
            get {
                return ResourceManager.GetString("Titulo_CameraNaoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Titulo_Favoritos {
            get {
                return ResourceManager.GetString("Titulo_Favoritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        public static string Titulo_PermissaoFotoNegada {
            get {
                return ResourceManager.GetString("Titulo_PermissaoFotoNegada", resourceCulture);
            }
        }
    }
}
